### ISSUE TITLE
Invalid nonce error

### ISSUE THREAD

**Issue by jasonmellone** [kmadac/bitstamp-python-client#18]
Hello,

I posted the question on stackoverflow, but I am getting the following error when using a valid user/key/secret.

http://stackoverflow.com/questions/24285109/python-bitstamp-api-invalid-nonce-error

Unsure what I can do to solve this or what I have done wrong. Please let me know if this is a bug or not as I would love to get it solved. Happy to contribute in modifying the code, but unsure why this is occurring.

This login was working up until it sporadically stopped working yesterday evening.

**Comment by kmadac** [comment]
Closed because no reaction for a long time.
