### ISSUE TITLE
Can we do a stop order or stop trail order?

### ISSUE THREAD

**Issue by TheLegendAli** [kmadac/bitstamp-python-client#28]
I couldnt find it in documention. If so please guide

**Comment by kmadac** [comment]
Bitstamp API have exposed Buy/Sell limit order and Buy/Sell Market order and these are implemented already.
You can find it in source code here: https://github.com/kmadac/bitstamp-python-client/blob/582a9ae5c3810987a45db0f3dbdf7a9b6d203591/bitstamp/client.py#L305

Is this what you are looking for?

**Comment by TheLegendAli** [comment]
Nope.

On bitstamp you can make market, limit and stop orders. https://www.bitstamp.net/market/order/stop/

I want a way to make stop orders through the api

**Comment by kmadac** [comment]
As this project is only wrapper of Bitstamp REST API  and the API doesn't expose such functionality, we cannot add it. Once Bitstamp will add it I can add it as well in matter of hours.

**Comment by TheLegendAli** [comment]
Thats what I thought.

Anyway thanks for your efforts

**Comment by TheLegendAli** [comment]
Actually one follow-up question:

is there a way that we can include the limit_price in the limit order?

Bitstamp APi allows for the price amount and limit_price amount for the limit order. I'm not sure how we can include that in the python wrapper.

https://www.bitstamp.net/api/

**Comment by Deelight-fr** [comment]
limit_price argument wad added thorugh merge https://github.com/kmadac/bitstamp-python-client/pull/30
