### ISSUE TITLE
Other Currencys Price

### ISSUE THREAD

**Issue by stefansill** [kmadac/bitstamp-python-client#35]
Getting the bid Price of BTC witth "public_client.ticker()['bid']" works fine, how can i get the prices of ETH for example?

**Comment by jorijnsmit** [comment]
You have to redefine `base` when calling `ticker()`. See the source at [bitstamp/client.py#L106](https://github.com/kmadac/bitstamp-python-client/blob/35b9a61f3892cc281de89963d210f7bd5757c717/bitstamp/client.py#L106).
Try `public_client.ticker(base='eth')['bid']`

**Comment by stefansill** [comment]
Thanks for the fast answer
