### ISSUE TITLE
order status 'In queue'

### ISSUE THREAD

**Issue by LiYijin** [kmadac/bitstamp-python-client#39]
when i place a limit order, I sometimes , the order status is "In queue", which lasts for several seconds. And then, it becomes 'open', whats is the meaning of "in queue"

**Comment by kmadac** [comment]
Hi, I have never noticed that, but It's probably the way how bitstamp
service itself handles the requests. It has nothing to do with python
client, so if order is succesfully opened you can ignore it.

**Comment by kmadac** [comment]
As no new updates are added for more than a year, I'm closing the issue.
