### ISSUE TITLE
why isn't the code updated to the 2.2.5 version? setup file still says 2.2.4....

### ISSUE THREAD

**Issue by GiusyColarusso** [kmadac/bitstamp-python-client#44]

**Comment by kmadac** [comment]
Thanks for pointing out that version is not updated. I somehow forgot to push commit where version has been updated. Only tag 2.2.5 has been pushed. Also thanks for PR, but as I pushed existing commit from my own repo, I will close it.

**Comment by GiusyColarusso** [comment]
Thank you for your reply.
When I try to make an order using Bitstamp api I get this error: (I tired to contact Bitstamp support but they told me that I have to contact the author of the code):

Traceback (most recent call last):
  File "Marangia.py", line 41, in <module>
    trading_client.sell_market_order(amount=amount_tosell, base="btc", quote="usd")
  File "/Users/Giusy/anaconda3/lib/python3.6/site-packages/bitstamp/client.py", line 354, in sell_market_order
    return self._post(url, data=data, return_json=True, version=2)
  File "/Users/Giusy/anaconda3/lib/python3.6/site-packages/bitstamp/client.py", line 48, in _post
    return self._request(requests.post, *args, **kwargs)
  File "/Users/Giusy/anaconda3/lib/python3.6/site-packages/bitstamp/client.py", line 82, in _request
    response.raise_for_status()
  File "/Users/Giusy/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Authentication Failed for url: https://www.bitstamp.net/api/v2/sell/market/btcusd/

A few times it works but the majority of times it doesn’t…
Please Help me solve this problem, what can I do?

thank you so much!


Il giorno 11 giu 2019, alle ore 14:26, Kamil Madac <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Thanks for pointing out that version is not updated. I somehow forgot to push commit where version has been updated. Only tag 2.2.5 has been pushed. Also thanks for PR, but as I pushed existing commit from my own repo, I will close it.

**Comment by kmadac** [comment]
Could you please create different issue for you question? I will check it asap.
