### ISSUE TITLE
New bitstamp api version (v2)

### ISSUE THREAD

**Issue by pepi99** [kmadac/bitstamp-python-client#49]
`API v1 authentication and v1 endpoints are being deprecated and are no longer documented on this page. For now you can still access API v1 documentation [here](https://www.bitstamp.net/api-deprecated/)[](https://www.bitstamp.net/api/#top).`

This library uses the v1 of the bitmap API, please account for this when using it.

**Comment by pepi99** [comment]
https://www.bitstamp.net/api/

**Comment by kmadac** [comment]
Hi, it has support for both versions, but some functions which can be used in both versions defaults to v1.
